import streamlit as st
from PIL import Image
import torch

# Import prediction function from inference file
from model_inference import predict, CLASS_NAMES

# =============================
# Page Config
# =============================
st.set_page_config(
    page_title="DeepFake Detector",
    page_icon="🧠",
    layout="centered"
)

# =============================
# Title
# =============================
st.title("🧠 DeepFake Detection System")
st.write(
    "Upload an image and the model will predict whether it is **Original** "
    "or generated by a **DeepFake technique**."
)

st.markdown("---")

# =============================
# Image Upload
# =============================
uploaded_file = st.file_uploader(
    "Upload a face image",
    type=["jpg", "jpeg", "png"]
)

# =============================
# Prediction
# =============================
if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(image, caption="Uploaded Image", use_column_width=True)

    st.write("🔍 Running model inference...")

    label, confidence = predict(image)

    st.markdown("---")

    st.subheader("Prediction Result")

    st.success(f"Prediction: **{label}**")

    st.metric(
        label="Confidence",
        value=f"{confidence*100:.2f}%"
    )

    st.markdown("---")

    st.write("### All Possible Classes")
    st.write(CLASS_NAMES)

else:
    st.info("Please upload an image to start detection.")
